services:
  centrum-wiedzy:
    build: .
    ports:
      - "4321:4321"
    volumes:
      - ./src/content:/app/src/content
      - ./src/data:/app/src/data
      - ./public/maps:/app/public/maps
      - ./public/maps:/app/dist/client/maps
    environment:
      - HOST=0.0.0.0
      - PORT=4321
    restart: always
